# Generated by Django 5.0.6 on 2024-08-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_user_type_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('HR', 'HR'), ('Candidate', 'Candidate')], default='Candidate', max_length=10),
        ),
    ]
