# Generated by Django 5.0.6 on 2024-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
