# Generated by Django 5.0.6 on 2024-08-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobapplication_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='function',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='schedule',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
