# Generated by Django 5.0.6 on 2024-09-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('payments', '0002_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post', to='payments.order'),
        ),
    ]
