# Generated by Django 5.0.6 on 2024-08-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='about',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='social_network_profile',
        ),
    ]
