# Generated by Django 5.0.6 on 2024-08-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='match_score',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
