# Generated by Django 5.0.6 on 2024-08-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobapplication_applicant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='resume',
            new_name='cv',
        ),
    ]
